linters:
  enable-all: true
  disable:
    - gofumpt # Only formatting
    - godot # Only formatting
    - varnamelen # Imho not important
    - wrapcheck # This project does not use error wrapping
    - paralleltest # This project is not using parallel testing
    - nlreturn # Only formatting
    - ireturn # This project sometimes uses interfaces
    - gochecknoglobals # This project still uses some global variables
    - exhaustruct # This projects relies on using only parts of structs
    - errorlint # This project has not yet moved to static errors
    - wsl # Formatting
    - misspell # My english is just not that good
    - lll # Formatting
    - tagliatelle # Formatting
    - gochecknoinits # issue 84
    - gocritic # Formatting
    - godox # Formatting
    - durationcheck # Using duration multiplication a few times
    - gci # Formatting
    - nonamedreturns # Do not agree with this linter
    - stylecheck # Formatting
    - testpackage # Naming
    - exhaustive # To many false positives
    - interfacebloat # Do not agree
    # deprecated
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - tenv

linters-settings:
  cyclop:
    max-complexity: 30
  funlen:
    lines: 150
    statements: 80
  gocognit:
    min-complexity: 40 # not ideal, should be improved

  depguard:
    rules:
      main:
        deny:
          - pkg: github.com/tj/assert
            desc: github.com/stretchr/testify/assert is preferred

issues:
  exclude: 
    - "var-naming: don't use an underscore in package name"
  exclude-rules:
    - path: '(.*)_test\.go'
      linters:
        - funlen
        - forcetypeassert
        - goconst
        - noctx
        - forbidigo
