displayName: GeoIP Metrics & Country Header
type: middleware

import: github.com/Cubicroots-Playground/traefik-geoip-metrics-middleware

summary: 'Sends source IPs to a sidecar that exposes GeoIP based metrics and injects the country code as a header.'

testData:
  geoipApi: "http://geoip-api:8080"
